### ISSUE TITLE
InfernoRouter with TransitionGroup animation

### ISSUE THREAD

**Issue by atwaves** [infernojs/inferno-transition-group#2]
Hi, with react & react-router this feature is working,

[http://codepen.io/artemxgruden/pen/MJZyda](http://codepen.io/artemxgruden/pen/MJZyda),

but if I using Inferno analogs in **Parent** component
```
<TransitionGroup>

                    {
                        [0].map( (item, i) => {

                            return Inferno.cloneVNode( this.props.children, {key: Math.random } )

                        } )

                    }
                        
                </TransitionGroup>
```
animations are not available.

Please help

**Comment by Havunen** [comment]
If this is still an issue, please re-open.
