### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by LexRiver** [infernojs/inferno-transition-group#4]
Hello, could you please update to match the latest version of ```react-transition-group```?
And I miss ```CSSTransitionGroup``` also.

I've tried your example from test and it works incorrectly for me for the ```componentWillLeave``` event.
If I remove item from middle, this item disappears immediately and all other items moves up, except for the last one. And I got the following warning:
```Inferno normalisation(...): Encountered two children with same key, all keys must be unique within its siblings. Duplicated key is:me```

but the same example works fine for me for ```react-transition-group```.

**Comment by Havunen** [comment]
The bug you described is most likely fixed today? https://github.com/infernojs/inferno-transition-group/pull/3

**Comment by Havunen** [comment]
Are you able to send PR for updating this project?

**Comment by kurdin** [comment]
@Havunen could you please release new version to npm? 

@LexRiver you can try https://github.com/kurdin/velocity-inferno better than CSSTransitionGroup

**Comment by Havunen** [comment]
Published current version to NPM

**Comment by LexRiver** [comment]
yes, works correctly now

**Comment by Havunen** [comment]
Okay, closing :)

**Comment by Havunen** [comment]
Oh nvm, we could still use this ticket as reference for update task.
